### ISSUE TITLE
Deployment Problem - "Resource with id [ApiGatewayApi] is invalid."

### ISSUE THREAD

**Issue by tnl25** [aws-samples/aws-developer-workshop#2]
<img width="1440" alt="screen shot 2018-02-22 at 5 44 45 pm" src="https://user-images.githubusercontent.com/10964707/36574035-7fad72d4-17f8-11e8-94b6-5d7ae143c450.png">

**Comment by anshrma** [comment]
@tnl25 .. Thanks for reporting this. This is because of the answer key under nothing/to/see/here/template.yml has few additional resources, which are not desired in the solution, thus, should not be copied. Here is the correct template.yml which works. Give it a try and let me know if all good. We are getting this updated in nothing/to/see/here/template.yml as well (source for which is not in this repository)

```
AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  AddService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add.handler
      Runtime: nodejs6.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /add/{x}/{y}
            Method: any
```
